# [helpers]

# [default]
# depends = []
# 
# [default.files]
# "README.md" = ""
#
# [default.variables]

[bash.files]
".bash_profile" = "~/.bash_profile"
".bashrc" = "~/.bashrc"
".profile" = "~/.profile"

[git.files]
".gitconfig" = "~/.gitconfig"

[zsh.files]
".zshrc" = "~/.zshrc"

[neovim.files]
".config/nvim/dein.toml" = "~/.config/nvim/dein.toml"
".config/nvim/init.vim" = "~/.config/nvim/init.vim"

[sshd.files]
".ssh/authorized_keys" = "~/.ssh/authorized_keys"

